### ISSUE TITLE
Cannot add the integration

### ISSUE THREAD

**Issue by Next9999** [anthonysecco/public-lands-ha-sensor#3]
i was able to add it in Hacs, restart HA, but not able to add in the integration

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 8:44:22 AM (1 occurrence)
Last logged: 8:44:22 AM

Error setting up entry Public Lands for public_lands
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/public_lands/__init__.py", line 13, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by anthonysecco** [comment]
Try installing this patched version from the [dev branch](https://github.com/anthonysecco/public-lands-ha-sensor/tree/dev).

**Comment by Next9999** [comment]
![Image](https://github.com/user-attachments/assets/2fdcca08-1e3e-4a90-b5d2-dd0a1d252967)

**Comment by taisau** [comment]
AI said 
> Looking at the error, the issue is that async_forward_entry_setup method doesn't exist. The correct method name is async_forward_entry_setups (plural) or you need to use await with the individual setup calls.

Made the change, and it seems to have fixed it.

**Comment by taisau** [comment]
All the latest versions. No rush here, thanks!
Installation method Home Assistant OS
Core 2025.6.0
Supervisor 2025.05.5
Operating System 15.2
Frontend 20250531.2

**Comment by anthonysecco** [comment]
I had done my development on an earlier version.  Turns out something I was relying on was deprecated in 2025.6.x

@taisau and @Next9999 

I've made changes and have it working on my instance of 2025.6.1.  Please try the dev branch and let me know your results

[](https://github.com/anthonysecco/public-lands-ha-sensor/tree/dev)

**Comment by anthonysecco** [comment]
Awesome.  I've merged it into main and created a new release (v0.2.2).

Now close your laptop and get out there! 🥾
